[tool.poetry]
name = "ndgr-client"
version = "0.1.0"
description = "NDGRClient: Nicolive NDGR Server Client"
authors = ["tsukumi <tsukumijima@users.noreply.github.com>"]
license = "MIT"
readme = "Readme.md"

[tool.taskipy.tasks]
generate-proto = "find proto -name '*.proto' | xargs protoc --proto_path=proto --python_out=ndgr_client/proto --mypy_out=ndgr_client/proto"

[tool.poetry.dependencies]
python = ">=3.11,<3.13"
beautifulsoup4 = "^4.12.3"
httpx = {version = "^0.27.0", extras = ["http2"]}
pydantic = "^2.8.2"
typer = {version = "^0.12.3", extras = ["all"]}
typing-extensions = "^4.12.2"

[tool.poetry.group.dev.dependencies]
mypy-protobuf = "^3.6.0"
protobuf = "^5.27.2"
protoc-wheel-0 = "^27.0"
taskipy = "^1.13.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
