"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

from collections import abc as _abc
from google.protobuf import descriptor as _descriptor
from google.protobuf import duration_pb2 as _duration_pb2
from google.protobuf import message as _message
from google.protobuf.internal import containers as _containers
from google.protobuf.internal import enum_type_wrapper as _enum_type_wrapper
import builtins as _builtins
import sys
import typing as _typing

if sys.version_info >= (3, 10):
    from typing import TypeAlias as _TypeAlias
else:
    from typing_extensions import TypeAlias as _TypeAlias

DESCRIPTOR: _descriptor.FileDescriptor

@_typing.final
class Chat(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    class _AccountStatus:
        ValueType = _typing.NewType("ValueType", _builtins.int)
        V: _TypeAlias = ValueType  # noqa: Y015

    class _AccountStatusEnumTypeWrapper(_enum_type_wrapper._EnumTypeWrapper[Chat._AccountStatus.ValueType], _builtins.type):
        DESCRIPTOR: _descriptor.EnumDescriptor
        Standard: Chat._AccountStatus.ValueType  # 0
        Premium: Chat._AccountStatus.ValueType  # 1

    class AccountStatus(_AccountStatus, metaclass=_AccountStatusEnumTypeWrapper): ...
    Standard: Chat.AccountStatus.ValueType  # 0
    Premium: Chat.AccountStatus.ValueType  # 1

    @_typing.final
    class Modifier(_message.Message):
        DESCRIPTOR: _descriptor.Descriptor

        class _Pos:
            ValueType = _typing.NewType("ValueType", _builtins.int)
            V: _TypeAlias = ValueType  # noqa: Y015

        class _PosEnumTypeWrapper(_enum_type_wrapper._EnumTypeWrapper[Chat.Modifier._Pos.ValueType], _builtins.type):
            DESCRIPTOR: _descriptor.EnumDescriptor
            naka: Chat.Modifier._Pos.ValueType  # 0
            shita: Chat.Modifier._Pos.ValueType  # 1
            ue: Chat.Modifier._Pos.ValueType  # 2

        class Pos(_Pos, metaclass=_PosEnumTypeWrapper): ...
        naka: Chat.Modifier.Pos.ValueType  # 0
        shita: Chat.Modifier.Pos.ValueType  # 1
        ue: Chat.Modifier.Pos.ValueType  # 2

        class _Size:
            ValueType = _typing.NewType("ValueType", _builtins.int)
            V: _TypeAlias = ValueType  # noqa: Y015

        class _SizeEnumTypeWrapper(_enum_type_wrapper._EnumTypeWrapper[Chat.Modifier._Size.ValueType], _builtins.type):
            DESCRIPTOR: _descriptor.EnumDescriptor
            medium: Chat.Modifier._Size.ValueType  # 0
            small: Chat.Modifier._Size.ValueType  # 1
            big: Chat.Modifier._Size.ValueType  # 2

        class Size(_Size, metaclass=_SizeEnumTypeWrapper): ...
        medium: Chat.Modifier.Size.ValueType  # 0
        small: Chat.Modifier.Size.ValueType  # 1
        big: Chat.Modifier.Size.ValueType  # 2

        class _ColorName:
            ValueType = _typing.NewType("ValueType", _builtins.int)
            V: _TypeAlias = ValueType  # noqa: Y015

        class _ColorNameEnumTypeWrapper(_enum_type_wrapper._EnumTypeWrapper[Chat.Modifier._ColorName.ValueType], _builtins.type):
            DESCRIPTOR: _descriptor.EnumDescriptor
            white: Chat.Modifier._ColorName.ValueType  # 0
            red: Chat.Modifier._ColorName.ValueType  # 1
            pink: Chat.Modifier._ColorName.ValueType  # 2
            orange: Chat.Modifier._ColorName.ValueType  # 3
            yellow: Chat.Modifier._ColorName.ValueType  # 4
            green: Chat.Modifier._ColorName.ValueType  # 5
            cyan: Chat.Modifier._ColorName.ValueType  # 6
            blue: Chat.Modifier._ColorName.ValueType  # 7
            purple: Chat.Modifier._ColorName.ValueType  # 8
            black: Chat.Modifier._ColorName.ValueType  # 9
            white2: Chat.Modifier._ColorName.ValueType  # 10
            red2: Chat.Modifier._ColorName.ValueType  # 11
            pink2: Chat.Modifier._ColorName.ValueType  # 12
            orange2: Chat.Modifier._ColorName.ValueType  # 13
            yellow2: Chat.Modifier._ColorName.ValueType  # 14
            green2: Chat.Modifier._ColorName.ValueType  # 15
            cyan2: Chat.Modifier._ColorName.ValueType  # 16
            blue2: Chat.Modifier._ColorName.ValueType  # 17
            purple2: Chat.Modifier._ColorName.ValueType  # 18
            black2: Chat.Modifier._ColorName.ValueType  # 19

        class ColorName(_ColorName, metaclass=_ColorNameEnumTypeWrapper): ...
        white: Chat.Modifier.ColorName.ValueType  # 0
        red: Chat.Modifier.ColorName.ValueType  # 1
        pink: Chat.Modifier.ColorName.ValueType  # 2
        orange: Chat.Modifier.ColorName.ValueType  # 3
        yellow: Chat.Modifier.ColorName.ValueType  # 4
        green: Chat.Modifier.ColorName.ValueType  # 5
        cyan: Chat.Modifier.ColorName.ValueType  # 6
        blue: Chat.Modifier.ColorName.ValueType  # 7
        purple: Chat.Modifier.ColorName.ValueType  # 8
        black: Chat.Modifier.ColorName.ValueType  # 9
        white2: Chat.Modifier.ColorName.ValueType  # 10
        red2: Chat.Modifier.ColorName.ValueType  # 11
        pink2: Chat.Modifier.ColorName.ValueType  # 12
        orange2: Chat.Modifier.ColorName.ValueType  # 13
        yellow2: Chat.Modifier.ColorName.ValueType  # 14
        green2: Chat.Modifier.ColorName.ValueType  # 15
        cyan2: Chat.Modifier.ColorName.ValueType  # 16
        blue2: Chat.Modifier.ColorName.ValueType  # 17
        purple2: Chat.Modifier.ColorName.ValueType  # 18
        black2: Chat.Modifier.ColorName.ValueType  # 19

        class _Font:
            ValueType = _typing.NewType("ValueType", _builtins.int)
            V: _TypeAlias = ValueType  # noqa: Y015

        class _FontEnumTypeWrapper(_enum_type_wrapper._EnumTypeWrapper[Chat.Modifier._Font.ValueType], _builtins.type):
            DESCRIPTOR: _descriptor.EnumDescriptor
            defont: Chat.Modifier._Font.ValueType  # 0
            mincho: Chat.Modifier._Font.ValueType  # 1
            gothic: Chat.Modifier._Font.ValueType  # 2

        class Font(_Font, metaclass=_FontEnumTypeWrapper): ...
        defont: Chat.Modifier.Font.ValueType  # 0
        mincho: Chat.Modifier.Font.ValueType  # 1
        gothic: Chat.Modifier.Font.ValueType  # 2

        class _Opacity:
            ValueType = _typing.NewType("ValueType", _builtins.int)
            V: _TypeAlias = ValueType  # noqa: Y015

        class _OpacityEnumTypeWrapper(_enum_type_wrapper._EnumTypeWrapper[Chat.Modifier._Opacity.ValueType], _builtins.type):
            DESCRIPTOR: _descriptor.EnumDescriptor
            Normal: Chat.Modifier._Opacity.ValueType  # 0
            Translucent: Chat.Modifier._Opacity.ValueType  # 1

        class Opacity(_Opacity, metaclass=_OpacityEnumTypeWrapper): ...
        Normal: Chat.Modifier.Opacity.ValueType  # 0
        Translucent: Chat.Modifier.Opacity.ValueType  # 1

        @_typing.final
        class FullColor(_message.Message):
            DESCRIPTOR: _descriptor.Descriptor

            R_FIELD_NUMBER: _builtins.int
            G_FIELD_NUMBER: _builtins.int
            B_FIELD_NUMBER: _builtins.int
            r: _builtins.int
            g: _builtins.int
            b: _builtins.int
            def __init__(
                self,
                *,
                r: _builtins.int = ...,
                g: _builtins.int = ...,
                b: _builtins.int = ...,
            ) -> None: ...
            _ClearFieldArgType: _TypeAlias = _typing.Literal["b", b"b", "g", b"g", "r", b"r"]  # noqa: Y015
            def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

        POSITION_FIELD_NUMBER: _builtins.int
        SIZE_FIELD_NUMBER: _builtins.int
        NAMED_COLOR_FIELD_NUMBER: _builtins.int
        FULL_COLOR_FIELD_NUMBER: _builtins.int
        FONT_FIELD_NUMBER: _builtins.int
        OPACITY_FIELD_NUMBER: _builtins.int
        position: Global___Chat.Modifier.Pos.ValueType
        size: Global___Chat.Modifier.Size.ValueType
        named_color: Global___Chat.Modifier.ColorName.ValueType
        font: Global___Chat.Modifier.Font.ValueType
        opacity: Global___Chat.Modifier.Opacity.ValueType
        @_builtins.property
        def full_color(self) -> Global___Chat.Modifier.FullColor: ...
        def __init__(
            self,
            *,
            position: Global___Chat.Modifier.Pos.ValueType = ...,
            size: Global___Chat.Modifier.Size.ValueType = ...,
            named_color: Global___Chat.Modifier.ColorName.ValueType = ...,
            full_color: Global___Chat.Modifier.FullColor | None = ...,
            font: Global___Chat.Modifier.Font.ValueType = ...,
            opacity: Global___Chat.Modifier.Opacity.ValueType = ...,
        ) -> None: ...
        _HasFieldArgType: _TypeAlias = _typing.Literal["color", b"color", "full_color", b"full_color", "named_color", b"named_color"]  # noqa: Y015
        def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
        _ClearFieldArgType: _TypeAlias = _typing.Literal["color", b"color", "font", b"font", "full_color", b"full_color", "named_color", b"named_color", "opacity", b"opacity", "position", b"position", "size", b"size"]  # noqa: Y015
        def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
        _WhichOneofReturnType_color: _TypeAlias = _typing.Literal["named_color", "full_color"]  # noqa: Y015
        _WhichOneofArgType_color: _TypeAlias = _typing.Literal["color", b"color"]  # noqa: Y015
        def WhichOneof(self, oneof_group: _WhichOneofArgType_color) -> _WhichOneofReturnType_color | None: ...

    CONTENT_FIELD_NUMBER: _builtins.int
    VPOS_FIELD_NUMBER: _builtins.int
    ACCOUNT_STATUS_FIELD_NUMBER: _builtins.int
    NAME_FIELD_NUMBER: _builtins.int
    RAW_USER_ID_FIELD_NUMBER: _builtins.int
    HASHED_USER_ID_FIELD_NUMBER: _builtins.int
    MODIFIER_FIELD_NUMBER: _builtins.int
    NO_FIELD_NUMBER: _builtins.int
    content: _builtins.str
    vpos: _builtins.int
    account_status: Global___Chat.AccountStatus.ValueType
    name: _builtins.str
    raw_user_id: _builtins.int
    hashed_user_id: _builtins.str
    no: _builtins.int
    @_builtins.property
    def modifier(self) -> Global___Chat.Modifier: ...
    def __init__(
        self,
        *,
        content: _builtins.str = ...,
        vpos: _builtins.int = ...,
        account_status: Global___Chat.AccountStatus.ValueType = ...,
        name: _builtins.str | None = ...,
        raw_user_id: _builtins.int | None = ...,
        hashed_user_id: _builtins.str | None = ...,
        modifier: Global___Chat.Modifier | None = ...,
        no: _builtins.int = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["_hashed_user_id", b"_hashed_user_id", "_name", b"_name", "_raw_user_id", b"_raw_user_id", "hashed_user_id", b"hashed_user_id", "modifier", b"modifier", "name", b"name", "raw_user_id", b"raw_user_id"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["_hashed_user_id", b"_hashed_user_id", "_name", b"_name", "_raw_user_id", b"_raw_user_id", "account_status", b"account_status", "content", b"content", "hashed_user_id", b"hashed_user_id", "modifier", b"modifier", "name", b"name", "no", b"no", "raw_user_id", b"raw_user_id", "vpos", b"vpos"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    _WhichOneofReturnType__hashed_user_id: _TypeAlias = _typing.Literal["hashed_user_id"]  # noqa: Y015
    _WhichOneofArgType__hashed_user_id: _TypeAlias = _typing.Literal["_hashed_user_id", b"_hashed_user_id"]  # noqa: Y015
    _WhichOneofReturnType__name: _TypeAlias = _typing.Literal["name"]  # noqa: Y015
    _WhichOneofArgType__name: _TypeAlias = _typing.Literal["_name", b"_name"]  # noqa: Y015
    _WhichOneofReturnType__raw_user_id: _TypeAlias = _typing.Literal["raw_user_id"]  # noqa: Y015
    _WhichOneofArgType__raw_user_id: _TypeAlias = _typing.Literal["_raw_user_id", b"_raw_user_id"]  # noqa: Y015
    @_typing.overload
    def WhichOneof(self, oneof_group: _WhichOneofArgType__hashed_user_id) -> _WhichOneofReturnType__hashed_user_id | None: ...
    @_typing.overload
    def WhichOneof(self, oneof_group: _WhichOneofArgType__name) -> _WhichOneofReturnType__name | None: ...
    @_typing.overload
    def WhichOneof(self, oneof_group: _WhichOneofArgType__raw_user_id) -> _WhichOneofReturnType__raw_user_id | None: ...

Global___Chat: _TypeAlias = Chat  # noqa: Y015

@_typing.final
class OperatorComment(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    CONTENT_FIELD_NUMBER: _builtins.int
    NAME_FIELD_NUMBER: _builtins.int
    MODIFIER_FIELD_NUMBER: _builtins.int
    LINK_FIELD_NUMBER: _builtins.int
    content: _builtins.str
    name: _builtins.str
    link: _builtins.str
    @_builtins.property
    def modifier(self) -> Global___Chat.Modifier: ...
    def __init__(
        self,
        *,
        content: _builtins.str = ...,
        name: _builtins.str | None = ...,
        modifier: Global___Chat.Modifier | None = ...,
        link: _builtins.str | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["_link", b"_link", "_name", b"_name", "link", b"link", "modifier", b"modifier", "name", b"name"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["_link", b"_link", "_name", b"_name", "content", b"content", "link", b"link", "modifier", b"modifier", "name", b"name"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    _WhichOneofReturnType__link: _TypeAlias = _typing.Literal["link"]  # noqa: Y015
    _WhichOneofArgType__link: _TypeAlias = _typing.Literal["_link", b"_link"]  # noqa: Y015
    _WhichOneofReturnType__name: _TypeAlias = _typing.Literal["name"]  # noqa: Y015
    _WhichOneofArgType__name: _TypeAlias = _typing.Literal["_name", b"_name"]  # noqa: Y015
    @_typing.overload
    def WhichOneof(self, oneof_group: _WhichOneofArgType__link) -> _WhichOneofReturnType__link | None: ...
    @_typing.overload
    def WhichOneof(self, oneof_group: _WhichOneofArgType__name) -> _WhichOneofReturnType__name | None: ...

Global___OperatorComment: _TypeAlias = OperatorComment  # noqa: Y015

@_typing.final
class Jump(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    CONTENT_FIELD_NUMBER: _builtins.int
    MESSAGE_FIELD_NUMBER: _builtins.int
    WAIT_FIELD_NUMBER: _builtins.int
    content: _builtins.str
    message: _builtins.str
    @_builtins.property
    def wait(self) -> _duration_pb2.Duration: ...
    def __init__(
        self,
        *,
        content: _builtins.str = ...,
        message: _builtins.str = ...,
        wait: _duration_pb2.Duration | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["wait", b"wait"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["content", b"content", "message", b"message", "wait", b"wait"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___Jump: _TypeAlias = Jump  # noqa: Y015

@_typing.final
class Redirect(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    URI_FIELD_NUMBER: _builtins.int
    MESSAGE_FIELD_NUMBER: _builtins.int
    WAIT_FIELD_NUMBER: _builtins.int
    uri: _builtins.str
    message: _builtins.str
    @_builtins.property
    def wait(self) -> _duration_pb2.Duration: ...
    def __init__(
        self,
        *,
        uri: _builtins.str = ...,
        message: _builtins.str = ...,
        wait: _duration_pb2.Duration | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["wait", b"wait"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["message", b"message", "uri", b"uri", "wait", b"wait"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___Redirect: _TypeAlias = Redirect  # noqa: Y015

@_typing.final
class SimpleNotification(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    ICHIBA_FIELD_NUMBER: _builtins.int
    QUOTE_FIELD_NUMBER: _builtins.int
    EMOTION_FIELD_NUMBER: _builtins.int
    CRUISE_FIELD_NUMBER: _builtins.int
    PROGRAM_EXTENDED_FIELD_NUMBER: _builtins.int
    RANKING_IN_FIELD_NUMBER: _builtins.int
    RANKING_UPDATED_FIELD_NUMBER: _builtins.int
    VISITED_FIELD_NUMBER: _builtins.int
    SUPPORTER_REGISTERED_FIELD_NUMBER: _builtins.int
    USER_LEVEL_UP_FIELD_NUMBER: _builtins.int
    ichiba: _builtins.str
    quote: _builtins.str
    emotion: _builtins.str
    cruise: _builtins.str
    program_extended: _builtins.str
    ranking_in: _builtins.str
    ranking_updated: _builtins.str
    visited: _builtins.str
    supporter_registered: _builtins.str
    user_level_up: _builtins.str
    def __init__(
        self,
        *,
        ichiba: _builtins.str = ...,
        quote: _builtins.str = ...,
        emotion: _builtins.str = ...,
        cruise: _builtins.str = ...,
        program_extended: _builtins.str = ...,
        ranking_in: _builtins.str = ...,
        ranking_updated: _builtins.str = ...,
        visited: _builtins.str = ...,
        supporter_registered: _builtins.str = ...,
        user_level_up: _builtins.str = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["cruise", b"cruise", "emotion", b"emotion", "ichiba", b"ichiba", "message", b"message", "program_extended", b"program_extended", "quote", b"quote", "ranking_in", b"ranking_in", "ranking_updated", b"ranking_updated", "supporter_registered", b"supporter_registered", "user_level_up", b"user_level_up", "visited", b"visited"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["cruise", b"cruise", "emotion", b"emotion", "ichiba", b"ichiba", "message", b"message", "program_extended", b"program_extended", "quote", b"quote", "ranking_in", b"ranking_in", "ranking_updated", b"ranking_updated", "supporter_registered", b"supporter_registered", "user_level_up", b"user_level_up", "visited", b"visited"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    _WhichOneofReturnType_message: _TypeAlias = _typing.Literal["ichiba", "quote", "emotion", "cruise", "program_extended", "ranking_in", "ranking_updated", "visited", "supporter_registered", "user_level_up"]  # noqa: Y015
    _WhichOneofArgType_message: _TypeAlias = _typing.Literal["message", b"message"]  # noqa: Y015
    def WhichOneof(self, oneof_group: _WhichOneofArgType_message) -> _WhichOneofReturnType_message | None: ...

Global___SimpleNotification: _TypeAlias = SimpleNotification  # noqa: Y015

@_typing.final
class Gift(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    ITEM_ID_FIELD_NUMBER: _builtins.int
    ADVERTISER_USER_ID_FIELD_NUMBER: _builtins.int
    ADVERTISER_NAME_FIELD_NUMBER: _builtins.int
    POINT_FIELD_NUMBER: _builtins.int
    MESSAGE_FIELD_NUMBER: _builtins.int
    ITEM_NAME_FIELD_NUMBER: _builtins.int
    CONTRIBUTION_RANK_FIELD_NUMBER: _builtins.int
    item_id: _builtins.str
    advertiser_user_id: _builtins.int
    advertiser_name: _builtins.str
    point: _builtins.int
    message: _builtins.str
    item_name: _builtins.str
    contribution_rank: _builtins.int
    def __init__(
        self,
        *,
        item_id: _builtins.str = ...,
        advertiser_user_id: _builtins.int | None = ...,
        advertiser_name: _builtins.str = ...,
        point: _builtins.int = ...,
        message: _builtins.str = ...,
        item_name: _builtins.str = ...,
        contribution_rank: _builtins.int | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["_advertiser_user_id", b"_advertiser_user_id", "_contribution_rank", b"_contribution_rank", "advertiser_user_id", b"advertiser_user_id", "contribution_rank", b"contribution_rank"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["_advertiser_user_id", b"_advertiser_user_id", "_contribution_rank", b"_contribution_rank", "advertiser_name", b"advertiser_name", "advertiser_user_id", b"advertiser_user_id", "contribution_rank", b"contribution_rank", "item_id", b"item_id", "item_name", b"item_name", "message", b"message", "point", b"point"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    _WhichOneofReturnType__advertiser_user_id: _TypeAlias = _typing.Literal["advertiser_user_id"]  # noqa: Y015
    _WhichOneofArgType__advertiser_user_id: _TypeAlias = _typing.Literal["_advertiser_user_id", b"_advertiser_user_id"]  # noqa: Y015
    _WhichOneofReturnType__contribution_rank: _TypeAlias = _typing.Literal["contribution_rank"]  # noqa: Y015
    _WhichOneofArgType__contribution_rank: _TypeAlias = _typing.Literal["_contribution_rank", b"_contribution_rank"]  # noqa: Y015
    @_typing.overload
    def WhichOneof(self, oneof_group: _WhichOneofArgType__advertiser_user_id) -> _WhichOneofReturnType__advertiser_user_id | None: ...
    @_typing.overload
    def WhichOneof(self, oneof_group: _WhichOneofArgType__contribution_rank) -> _WhichOneofReturnType__contribution_rank | None: ...

Global___Gift: _TypeAlias = Gift  # noqa: Y015

@_typing.final
class Nicoad(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    @_typing.final
    class V0(_message.Message):
        DESCRIPTOR: _descriptor.Descriptor

        @_typing.final
        class Latest(_message.Message):
            DESCRIPTOR: _descriptor.Descriptor

            ADVERTISER_FIELD_NUMBER: _builtins.int
            POINT_FIELD_NUMBER: _builtins.int
            MESSAGE_FIELD_NUMBER: _builtins.int
            advertiser: _builtins.str
            point: _builtins.int
            message: _builtins.str
            def __init__(
                self,
                *,
                advertiser: _builtins.str = ...,
                point: _builtins.int = ...,
                message: _builtins.str | None = ...,
            ) -> None: ...
            _HasFieldArgType: _TypeAlias = _typing.Literal["_message", b"_message", "message", b"message"]  # noqa: Y015
            def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
            _ClearFieldArgType: _TypeAlias = _typing.Literal["_message", b"_message", "advertiser", b"advertiser", "message", b"message", "point", b"point"]  # noqa: Y015
            def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
            _WhichOneofReturnType__message: _TypeAlias = _typing.Literal["message"]  # noqa: Y015
            _WhichOneofArgType__message: _TypeAlias = _typing.Literal["_message", b"_message"]  # noqa: Y015
            def WhichOneof(self, oneof_group: _WhichOneofArgType__message) -> _WhichOneofReturnType__message | None: ...

        @_typing.final
        class Ranking(_message.Message):
            DESCRIPTOR: _descriptor.Descriptor

            ADVERTISER_FIELD_NUMBER: _builtins.int
            RANK_FIELD_NUMBER: _builtins.int
            MESSAGE_FIELD_NUMBER: _builtins.int
            USER_RANK_FIELD_NUMBER: _builtins.int
            advertiser: _builtins.str
            rank: _builtins.int
            message: _builtins.str
            user_rank: _builtins.int
            def __init__(
                self,
                *,
                advertiser: _builtins.str = ...,
                rank: _builtins.int = ...,
                message: _builtins.str | None = ...,
                user_rank: _builtins.int | None = ...,
            ) -> None: ...
            _HasFieldArgType: _TypeAlias = _typing.Literal["_message", b"_message", "_user_rank", b"_user_rank", "message", b"message", "user_rank", b"user_rank"]  # noqa: Y015
            def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
            _ClearFieldArgType: _TypeAlias = _typing.Literal["_message", b"_message", "_user_rank", b"_user_rank", "advertiser", b"advertiser", "message", b"message", "rank", b"rank", "user_rank", b"user_rank"]  # noqa: Y015
            def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
            _WhichOneofReturnType__message: _TypeAlias = _typing.Literal["message"]  # noqa: Y015
            _WhichOneofArgType__message: _TypeAlias = _typing.Literal["_message", b"_message"]  # noqa: Y015
            _WhichOneofReturnType__user_rank: _TypeAlias = _typing.Literal["user_rank"]  # noqa: Y015
            _WhichOneofArgType__user_rank: _TypeAlias = _typing.Literal["_user_rank", b"_user_rank"]  # noqa: Y015
            @_typing.overload
            def WhichOneof(self, oneof_group: _WhichOneofArgType__message) -> _WhichOneofReturnType__message | None: ...
            @_typing.overload
            def WhichOneof(self, oneof_group: _WhichOneofArgType__user_rank) -> _WhichOneofReturnType__user_rank | None: ...

        LATEST_FIELD_NUMBER: _builtins.int
        RANKING_FIELD_NUMBER: _builtins.int
        TOTAL_POINT_FIELD_NUMBER: _builtins.int
        total_point: _builtins.int
        @_builtins.property
        def latest(self) -> Global___Nicoad.V0.Latest: ...
        @_builtins.property
        def ranking(self) -> _containers.RepeatedCompositeFieldContainer[Global___Nicoad.V0.Ranking]: ...
        def __init__(
            self,
            *,
            latest: Global___Nicoad.V0.Latest | None = ...,
            ranking: _abc.Iterable[Global___Nicoad.V0.Ranking] | None = ...,
            total_point: _builtins.int = ...,
        ) -> None: ...
        _HasFieldArgType: _TypeAlias = _typing.Literal["latest", b"latest"]  # noqa: Y015
        def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
        _ClearFieldArgType: _TypeAlias = _typing.Literal["latest", b"latest", "ranking", b"ranking", "total_point", b"total_point"]  # noqa: Y015
        def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

    @_typing.final
    class V1(_message.Message):
        DESCRIPTOR: _descriptor.Descriptor

        TOTAL_AD_POINT_FIELD_NUMBER: _builtins.int
        MESSAGE_FIELD_NUMBER: _builtins.int
        total_ad_point: _builtins.int
        message: _builtins.str
        def __init__(
            self,
            *,
            total_ad_point: _builtins.int = ...,
            message: _builtins.str = ...,
        ) -> None: ...
        _ClearFieldArgType: _TypeAlias = _typing.Literal["message", b"message", "total_ad_point", b"total_ad_point"]  # noqa: Y015
        def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

    V0_FIELD_NUMBER: _builtins.int
    V1_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def v0(self) -> Global___Nicoad.V0: ...
    @_builtins.property
    def v1(self) -> Global___Nicoad.V1: ...
    def __init__(
        self,
        *,
        v0: Global___Nicoad.V0 | None = ...,
        v1: Global___Nicoad.V1 | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["v0", b"v0", "v1", b"v1", "versions", b"versions"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["v0", b"v0", "v1", b"v1", "versions", b"versions"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    _WhichOneofReturnType_versions: _TypeAlias = _typing.Literal["v0", "v1"]  # noqa: Y015
    _WhichOneofArgType_versions: _TypeAlias = _typing.Literal["versions", b"versions"]  # noqa: Y015
    def WhichOneof(self, oneof_group: _WhichOneofArgType_versions) -> _WhichOneofReturnType_versions | None: ...

Global___Nicoad: _TypeAlias = Nicoad  # noqa: Y015

@_typing.final
class CommentLock(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    class _Status:
        ValueType = _typing.NewType("ValueType", _builtins.int)
        V: _TypeAlias = ValueType  # noqa: Y015

    class _StatusEnumTypeWrapper(_enum_type_wrapper._EnumTypeWrapper[CommentLock._Status.ValueType], _builtins.type):
        DESCRIPTOR: _descriptor.EnumDescriptor
        Unrestricted: CommentLock._Status.ValueType  # 0
        Locked: CommentLock._Status.ValueType  # 1
        Restricted: CommentLock._Status.ValueType  # 2

    class Status(_Status, metaclass=_StatusEnumTypeWrapper): ...
    Unrestricted: CommentLock.Status.ValueType  # 0
    Locked: CommentLock.Status.ValueType  # 1
    Restricted: CommentLock.Status.ValueType  # 2

    @_typing.final
    class FollowRestriction(_message.Message):
        DESCRIPTOR: _descriptor.Descriptor

        MINIMUM_FOLLOW_DURATION_FIELD_NUMBER: _builtins.int
        @_builtins.property
        def minimum_follow_duration(self) -> _duration_pb2.Duration: ...
        def __init__(
            self,
            *,
            minimum_follow_duration: _duration_pb2.Duration | None = ...,
        ) -> None: ...
        _HasFieldArgType: _TypeAlias = _typing.Literal["minimum_follow_duration", b"minimum_follow_duration"]  # noqa: Y015
        def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
        _ClearFieldArgType: _TypeAlias = _typing.Literal["minimum_follow_duration", b"minimum_follow_duration"]  # noqa: Y015
        def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

    STATUS_FIELD_NUMBER: _builtins.int
    FOLLOW_RESTRICTION_FIELD_NUMBER: _builtins.int
    status: Global___CommentLock.Status.ValueType
    @_builtins.property
    def follow_restriction(self) -> Global___CommentLock.FollowRestriction: ...
    def __init__(
        self,
        *,
        status: Global___CommentLock.Status.ValueType = ...,
        follow_restriction: Global___CommentLock.FollowRestriction | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["_follow_restriction", b"_follow_restriction", "follow_restriction", b"follow_restriction"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["_follow_restriction", b"_follow_restriction", "follow_restriction", b"follow_restriction", "status", b"status"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    _WhichOneofReturnType__follow_restriction: _TypeAlias = _typing.Literal["follow_restriction"]  # noqa: Y015
    _WhichOneofArgType__follow_restriction: _TypeAlias = _typing.Literal["_follow_restriction", b"_follow_restriction"]  # noqa: Y015
    def WhichOneof(self, oneof_group: _WhichOneofArgType__follow_restriction) -> _WhichOneofReturnType__follow_restriction | None: ...

Global___CommentLock: _TypeAlias = CommentLock  # noqa: Y015

@_typing.final
class CommentMode(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    class _Layout:
        ValueType = _typing.NewType("ValueType", _builtins.int)
        V: _TypeAlias = ValueType  # noqa: Y015

    class _LayoutEnumTypeWrapper(_enum_type_wrapper._EnumTypeWrapper[CommentMode._Layout.ValueType], _builtins.type):
        DESCRIPTOR: _descriptor.EnumDescriptor
        Normal: CommentMode._Layout.ValueType  # 0
        SplitTop: CommentMode._Layout.ValueType  # 1
        Background: CommentMode._Layout.ValueType  # 2

    class Layout(_Layout, metaclass=_LayoutEnumTypeWrapper): ...
    Normal: CommentMode.Layout.ValueType  # 0
    SplitTop: CommentMode.Layout.ValueType  # 1
    Background: CommentMode.Layout.ValueType  # 2

    LAYOUT_FIELD_NUMBER: _builtins.int
    layout: Global___CommentMode.Layout.ValueType
    def __init__(
        self,
        *,
        layout: Global___CommentMode.Layout.ValueType = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["layout", b"layout"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___CommentMode: _TypeAlias = CommentMode  # noqa: Y015

@_typing.final
class GameUpdate(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    def __init__(
        self,
    ) -> None: ...

Global___GameUpdate: _TypeAlias = GameUpdate  # noqa: Y015

@_typing.final
class TrialPanel(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    class _Panel:
        ValueType = _typing.NewType("ValueType", _builtins.int)
        V: _TypeAlias = ValueType  # noqa: Y015

    class _PanelEnumTypeWrapper(_enum_type_wrapper._EnumTypeWrapper[TrialPanel._Panel.ValueType], _builtins.type):
        DESCRIPTOR: _descriptor.EnumDescriptor
        Hidden: TrialPanel._Panel.ValueType  # 0
        Display: TrialPanel._Panel.ValueType  # 1

    class Panel(_Panel, metaclass=_PanelEnumTypeWrapper): ...
    Hidden: TrialPanel.Panel.ValueType  # 0
    Display: TrialPanel.Panel.ValueType  # 1

    class _Mode:
        ValueType = _typing.NewType("ValueType", _builtins.int)
        V: _TypeAlias = ValueType  # noqa: Y015

    class _ModeEnumTypeWrapper(_enum_type_wrapper._EnumTypeWrapper[TrialPanel._Mode.ValueType], _builtins.type):
        DESCRIPTOR: _descriptor.EnumDescriptor
        Allowed: TrialPanel._Mode.ValueType  # 0
        Restricted: TrialPanel._Mode.ValueType  # 1
        Forbidden: TrialPanel._Mode.ValueType  # 2

    class Mode(_Mode, metaclass=_ModeEnumTypeWrapper): ...
    Allowed: TrialPanel.Mode.ValueType  # 0
    Restricted: TrialPanel.Mode.ValueType  # 1
    Forbidden: TrialPanel.Mode.ValueType  # 2

    PANEL_FIELD_NUMBER: _builtins.int
    UNQUALIFIED_USER_FIELD_NUMBER: _builtins.int
    panel: Global___TrialPanel.Panel.ValueType
    unqualified_user: Global___TrialPanel.Mode.ValueType
    def __init__(
        self,
        *,
        panel: Global___TrialPanel.Panel.ValueType = ...,
        unqualified_user: Global___TrialPanel.Mode.ValueType = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["panel", b"panel", "unqualified_user", b"unqualified_user"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___TrialPanel: _TypeAlias = TrialPanel  # noqa: Y015

@_typing.final
class ProgramStatus(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    class _State:
        ValueType = _typing.NewType("ValueType", _builtins.int)
        V: _TypeAlias = ValueType  # noqa: Y015

    class _StateEnumTypeWrapper(_enum_type_wrapper._EnumTypeWrapper[ProgramStatus._State.ValueType], _builtins.type):
        DESCRIPTOR: _descriptor.EnumDescriptor
        Unknown: ProgramStatus._State.ValueType  # 0
        Ended: ProgramStatus._State.ValueType  # 1

    class State(_State, metaclass=_StateEnumTypeWrapper): ...
    Unknown: ProgramStatus.State.ValueType  # 0
    Ended: ProgramStatus.State.ValueType  # 1

    STATE_FIELD_NUMBER: _builtins.int
    state: Global___ProgramStatus.State.ValueType
    def __init__(
        self,
        *,
        state: Global___ProgramStatus.State.ValueType = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["state", b"state"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___ProgramStatus: _TypeAlias = ProgramStatus  # noqa: Y015

@_typing.final
class TagUpdated(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    @_typing.final
    class Tag(_message.Message):
        DESCRIPTOR: _descriptor.Descriptor

        TEXT_FIELD_NUMBER: _builtins.int
        LOCKED_FIELD_NUMBER: _builtins.int
        RESERVED_FIELD_NUMBER: _builtins.int
        NICOPEDIA_URI_FIELD_NUMBER: _builtins.int
        text: _builtins.str
        locked: _builtins.bool
        reserved: _builtins.bool
        nicopedia_uri: _builtins.str
        def __init__(
            self,
            *,
            text: _builtins.str = ...,
            locked: _builtins.bool = ...,
            reserved: _builtins.bool = ...,
            nicopedia_uri: _builtins.str | None = ...,
        ) -> None: ...
        _HasFieldArgType: _TypeAlias = _typing.Literal["_nicopedia_uri", b"_nicopedia_uri", "nicopedia_uri", b"nicopedia_uri"]  # noqa: Y015
        def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
        _ClearFieldArgType: _TypeAlias = _typing.Literal["_nicopedia_uri", b"_nicopedia_uri", "locked", b"locked", "nicopedia_uri", b"nicopedia_uri", "reserved", b"reserved", "text", b"text"]  # noqa: Y015
        def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
        _WhichOneofReturnType__nicopedia_uri: _TypeAlias = _typing.Literal["nicopedia_uri"]  # noqa: Y015
        _WhichOneofArgType__nicopedia_uri: _TypeAlias = _typing.Literal["_nicopedia_uri", b"_nicopedia_uri"]  # noqa: Y015
        def WhichOneof(self, oneof_group: _WhichOneofArgType__nicopedia_uri) -> _WhichOneofReturnType__nicopedia_uri | None: ...

    TAGS_FIELD_NUMBER: _builtins.int
    OWNER_LOCKED_FIELD_NUMBER: _builtins.int
    owner_locked: _builtins.bool
    @_builtins.property
    def tags(self) -> _containers.RepeatedCompositeFieldContainer[Global___TagUpdated.Tag]: ...
    def __init__(
        self,
        *,
        tags: _abc.Iterable[Global___TagUpdated.Tag] | None = ...,
        owner_locked: _builtins.bool = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["owner_locked", b"owner_locked", "tags", b"tags"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___TagUpdated: _TypeAlias = TagUpdated  # noqa: Y015

@_typing.final
class Statistics(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    VIEWERS_FIELD_NUMBER: _builtins.int
    COMMENTS_FIELD_NUMBER: _builtins.int
    AD_POINTS_FIELD_NUMBER: _builtins.int
    GIFT_POINTS_FIELD_NUMBER: _builtins.int
    TIMESHIFT_RESERVATIONS_FIELD_NUMBER: _builtins.int
    viewers: _builtins.int
    comments: _builtins.int
    ad_points: _builtins.int
    gift_points: _builtins.int
    timeshift_reservations: _builtins.int
    def __init__(
        self,
        *,
        viewers: _builtins.int | None = ...,
        comments: _builtins.int | None = ...,
        ad_points: _builtins.int | None = ...,
        gift_points: _builtins.int | None = ...,
        timeshift_reservations: _builtins.int | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["_ad_points", b"_ad_points", "_comments", b"_comments", "_gift_points", b"_gift_points", "_timeshift_reservations", b"_timeshift_reservations", "_viewers", b"_viewers", "ad_points", b"ad_points", "comments", b"comments", "gift_points", b"gift_points", "timeshift_reservations", b"timeshift_reservations", "viewers", b"viewers"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["_ad_points", b"_ad_points", "_comments", b"_comments", "_gift_points", b"_gift_points", "_timeshift_reservations", b"_timeshift_reservations", "_viewers", b"_viewers", "ad_points", b"ad_points", "comments", b"comments", "gift_points", b"gift_points", "timeshift_reservations", b"timeshift_reservations", "viewers", b"viewers"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    _WhichOneofReturnType__ad_points: _TypeAlias = _typing.Literal["ad_points"]  # noqa: Y015
    _WhichOneofArgType__ad_points: _TypeAlias = _typing.Literal["_ad_points", b"_ad_points"]  # noqa: Y015
    _WhichOneofReturnType__comments: _TypeAlias = _typing.Literal["comments"]  # noqa: Y015
    _WhichOneofArgType__comments: _TypeAlias = _typing.Literal["_comments", b"_comments"]  # noqa: Y015
    _WhichOneofReturnType__gift_points: _TypeAlias = _typing.Literal["gift_points"]  # noqa: Y015
    _WhichOneofArgType__gift_points: _TypeAlias = _typing.Literal["_gift_points", b"_gift_points"]  # noqa: Y015
    _WhichOneofReturnType__timeshift_reservations: _TypeAlias = _typing.Literal["timeshift_reservations"]  # noqa: Y015
    _WhichOneofArgType__timeshift_reservations: _TypeAlias = _typing.Literal["_timeshift_reservations", b"_timeshift_reservations"]  # noqa: Y015
    _WhichOneofReturnType__viewers: _TypeAlias = _typing.Literal["viewers"]  # noqa: Y015
    _WhichOneofArgType__viewers: _TypeAlias = _typing.Literal["_viewers", b"_viewers"]  # noqa: Y015
    @_typing.overload
    def WhichOneof(self, oneof_group: _WhichOneofArgType__ad_points) -> _WhichOneofReturnType__ad_points | None: ...
    @_typing.overload
    def WhichOneof(self, oneof_group: _WhichOneofArgType__comments) -> _WhichOneofReturnType__comments | None: ...
    @_typing.overload
    def WhichOneof(self, oneof_group: _WhichOneofArgType__gift_points) -> _WhichOneofReturnType__gift_points | None: ...
    @_typing.overload
    def WhichOneof(self, oneof_group: _WhichOneofArgType__timeshift_reservations) -> _WhichOneofReturnType__timeshift_reservations | None: ...
    @_typing.overload
    def WhichOneof(self, oneof_group: _WhichOneofArgType__viewers) -> _WhichOneofReturnType__viewers | None: ...

Global___Statistics: _TypeAlias = Statistics  # noqa: Y015

@_typing.final
class Marquee(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    @_typing.final
    class Display(_message.Message):
        DESCRIPTOR: _descriptor.Descriptor

        OPERATOR_COMMENT_FIELD_NUMBER: _builtins.int
        DURATION_FIELD_NUMBER: _builtins.int
        @_builtins.property
        def operator_comment(self) -> Global___OperatorComment: ...
        @_builtins.property
        def duration(self) -> _duration_pb2.Duration: ...
        def __init__(
            self,
            *,
            operator_comment: Global___OperatorComment | None = ...,
            duration: _duration_pb2.Duration | None = ...,
        ) -> None: ...
        _HasFieldArgType: _TypeAlias = _typing.Literal["_duration", b"_duration", "duration", b"duration", "operator_comment", b"operator_comment"]  # noqa: Y015
        def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
        _ClearFieldArgType: _TypeAlias = _typing.Literal["_duration", b"_duration", "duration", b"duration", "operator_comment", b"operator_comment"]  # noqa: Y015
        def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
        _WhichOneofReturnType__duration: _TypeAlias = _typing.Literal["duration"]  # noqa: Y015
        _WhichOneofArgType__duration: _TypeAlias = _typing.Literal["_duration", b"_duration"]  # noqa: Y015
        def WhichOneof(self, oneof_group: _WhichOneofArgType__duration) -> _WhichOneofReturnType__duration | None: ...

    DISPLAY_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def display(self) -> Global___Marquee.Display: ...
    def __init__(
        self,
        *,
        display: Global___Marquee.Display | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["_display", b"_display", "display", b"display"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["_display", b"_display", "display", b"display"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    _WhichOneofReturnType__display: _TypeAlias = _typing.Literal["display"]  # noqa: Y015
    _WhichOneofArgType__display: _TypeAlias = _typing.Literal["_display", b"_display"]  # noqa: Y015
    def WhichOneof(self, oneof_group: _WhichOneofArgType__display) -> _WhichOneofReturnType__display | None: ...

Global___Marquee: _TypeAlias = Marquee  # noqa: Y015

@_typing.final
class Enquete(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    class _Status:
        ValueType = _typing.NewType("ValueType", _builtins.int)
        V: _TypeAlias = ValueType  # noqa: Y015

    class _StatusEnumTypeWrapper(_enum_type_wrapper._EnumTypeWrapper[Enquete._Status.ValueType], _builtins.type):
        DESCRIPTOR: _descriptor.EnumDescriptor
        Closed: Enquete._Status.ValueType  # 0
        Poll: Enquete._Status.ValueType  # 1
        Result: Enquete._Status.ValueType  # 2

    class Status(_Status, metaclass=_StatusEnumTypeWrapper): ...
    Closed: Enquete.Status.ValueType  # 0
    Poll: Enquete.Status.ValueType  # 1
    Result: Enquete.Status.ValueType  # 2

    @_typing.final
    class Choice(_message.Message):
        DESCRIPTOR: _descriptor.Descriptor

        DESCRIPTION_FIELD_NUMBER: _builtins.int
        PER_MILLE_FIELD_NUMBER: _builtins.int
        description: _builtins.str
        per_mille: _builtins.int
        def __init__(
            self,
            *,
            description: _builtins.str = ...,
            per_mille: _builtins.int | None = ...,
        ) -> None: ...
        _HasFieldArgType: _TypeAlias = _typing.Literal["_per_mille", b"_per_mille", "per_mille", b"per_mille"]  # noqa: Y015
        def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
        _ClearFieldArgType: _TypeAlias = _typing.Literal["_per_mille", b"_per_mille", "description", b"description", "per_mille", b"per_mille"]  # noqa: Y015
        def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
        _WhichOneofReturnType__per_mille: _TypeAlias = _typing.Literal["per_mille"]  # noqa: Y015
        _WhichOneofArgType__per_mille: _TypeAlias = _typing.Literal["_per_mille", b"_per_mille"]  # noqa: Y015
        def WhichOneof(self, oneof_group: _WhichOneofArgType__per_mille) -> _WhichOneofReturnType__per_mille | None: ...

    QUESTION_FIELD_NUMBER: _builtins.int
    CHOICES_FIELD_NUMBER: _builtins.int
    STATUS_FIELD_NUMBER: _builtins.int
    question: _builtins.str
    status: Global___Enquete.Status.ValueType
    @_builtins.property
    def choices(self) -> _containers.RepeatedCompositeFieldContainer[Global___Enquete.Choice]: ...
    def __init__(
        self,
        *,
        question: _builtins.str = ...,
        choices: _abc.Iterable[Global___Enquete.Choice] | None = ...,
        status: Global___Enquete.Status.ValueType = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["choices", b"choices", "question", b"question", "status", b"status"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___Enquete: _TypeAlias = Enquete  # noqa: Y015

@_typing.final
class MoveOrder(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    JUMP_FIELD_NUMBER: _builtins.int
    REDIRECT_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def jump(self) -> Global___Jump: ...
    @_builtins.property
    def redirect(self) -> Global___Redirect: ...
    def __init__(
        self,
        *,
        jump: Global___Jump | None = ...,
        redirect: Global___Redirect | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["jump", b"jump", "redirect", b"redirect", "to", b"to"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["jump", b"jump", "redirect", b"redirect", "to", b"to"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    _WhichOneofReturnType_to: _TypeAlias = _typing.Literal["jump", "redirect"]  # noqa: Y015
    _WhichOneofArgType_to: _TypeAlias = _typing.Literal["to", b"to"]  # noqa: Y015
    def WhichOneof(self, oneof_group: _WhichOneofArgType_to) -> _WhichOneofReturnType_to | None: ...

Global___MoveOrder: _TypeAlias = MoveOrder  # noqa: Y015
