# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: dwango/nicolive/chat/data/message.proto
# Protobuf Python Version: 6.30.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    30,
    2,
    '',
    'dwango/nicolive/chat/data/message.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from ndgr_client.proto.dwango.nicolive.chat.data import atoms_pb2 as dwango_dot_nicolive_dot_chat_dot_data_dot_atoms__pb2
from ndgr_client.proto.dwango.nicolive.chat.data.atoms import forwarded_pb2 as dwango_dot_nicolive_dot_chat_dot_data_dot_atoms_dot_forwarded__pb2
from ndgr_client.proto.dwango.nicolive.chat.data.atoms import moderator_pb2 as dwango_dot_nicolive_dot_chat_dot_data_dot_atoms_dot_moderator__pb2
from ndgr_client.proto.dwango.nicolive.chat.data.atoms import notifications_pb2 as dwango_dot_nicolive_dot_chat_dot_data_dot_atoms_dot_notifications__pb2
from ndgr_client.proto.dwango.nicolive.chat.data.atoms import akashic_pb2 as dwango_dot_nicolive_dot_chat_dot_data_dot_atoms_dot_akashic__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\'dwango/nicolive/chat/data/message.proto\x12\x19\x64wango.nicolive.chat.data\x1a%dwango/nicolive/chat/data/atoms.proto\x1a/dwango/nicolive/chat/data/atoms/forwarded.proto\x1a/dwango/nicolive/chat/data/atoms/moderator.proto\x1a\x33\x64wango/nicolive/chat/data/atoms/notifications.proto\x1a-dwango/nicolive/chat/data/atoms/akashic.proto\"\xd8\x06\n\x0fNicoliveMessage\x12/\n\x04\x63hat\x18\x01 \x01(\x0b\x32\x1f.dwango.nicolive.chat.data.ChatH\x00\x12L\n\x13simple_notification\x18\x07 \x01(\x0b\x32-.dwango.nicolive.chat.data.SimpleNotificationH\x00\x12/\n\x04gift\x18\x08 \x01(\x0b\x32\x1f.dwango.nicolive.chat.data.GiftH\x00\x12\x33\n\x06nicoad\x18\t \x01(\x0b\x32!.dwango.nicolive.chat.data.NicoadH\x00\x12<\n\x0bgame_update\x18\r \x01(\x0b\x32%.dwango.nicolive.chat.data.GameUpdateH\x00\x12<\n\x0btag_updated\x18\x11 \x01(\x0b\x32%.dwango.nicolive.chat.data.TagUpdatedH\x00\x12N\n\x11moderator_updated\x18\x12 \x01(\x0b\x32\x31.dwango.nicolive.chat.data.atoms.ModeratorUpdatedH\x00\x12\x44\n\x0cssng_updated\x18\x13 \x01(\x0b\x32,.dwango.nicolive.chat.data.atoms.SSNGUpdatedH\x00\x12:\n\x0foverflowed_chat\x18\x14 \x01(\x0b\x32\x1f.dwango.nicolive.chat.data.ChatH\x00\x12H\n\x0e\x66orwarded_chat\x18\x16 \x01(\x0b\x32..dwango.nicolive.chat.data.atoms.ForwardedChatH\x00\x12W\n\x16simple_notification_v2\x18\x17 \x01(\x0b\x32\x35.dwango.nicolive.chat.data.atoms.SimpleNotificationV2H\x00\x12U\n\x15\x61kashic_message_event\x18\x18 \x01(\x0b\x32\x34.dwango.nicolive.chat.data.atoms.AkashicMessageEventH\x00\x42\x06\n\x04\x64\x61taJ\x04\x08\x02\x10\x07J\x04\x08\n\x10\rJ\x04\x08\x0e\x10\x11\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'dwango.nicolive.chat.data.message_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_NICOLIVEMESSAGE']._serialized_start=308
  _globals['_NICOLIVEMESSAGE']._serialized_end=1164
# @@protoc_insertion_point(module_scope)
