"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
import builtins as _builtins
import sys
import typing as _typing

if sys.version_info >= (3, 10):
    from typing import TypeAlias as _TypeAlias
else:
    from typing_extensions import TypeAlias as _TypeAlias

DESCRIPTOR: _descriptor.FileDescriptor

@_typing.final
class NicoliveOrigin(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    @_typing.final
    class Chat(_message.Message):
        DESCRIPTOR: _descriptor.Descriptor

        LIVE_ID_FIELD_NUMBER: _builtins.int
        live_id: _builtins.int
        def __init__(
            self,
            *,
            live_id: _builtins.int = ...,
        ) -> None: ...
        _ClearFieldArgType: _TypeAlias = _typing.Literal["live_id", b"live_id"]  # noqa: Y015
        def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

    CHAT_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def chat(self) -> Global___NicoliveOrigin.Chat: ...
    def __init__(
        self,
        *,
        chat: Global___NicoliveOrigin.Chat | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["chat", b"chat", "origin", b"origin"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["chat", b"chat", "origin", b"origin"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    _WhichOneofReturnType_origin: _TypeAlias = _typing.Literal["chat"]  # noqa: Y015
    _WhichOneofArgType_origin: _TypeAlias = _typing.Literal["origin", b"origin"]  # noqa: Y015
    def WhichOneof(self, oneof_group: _WhichOneofArgType_origin) -> _WhichOneofReturnType_origin | None: ...

Global___NicoliveOrigin: _TypeAlias = NicoliveOrigin  # noqa: Y015
