# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: dwango/nicolive/chat/data/atoms/akashic.proto
# Protobuf Python Version: 6.30.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    30,
    2,
    '',
    'dwango/nicolive/chat/data/atoms/akashic.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import struct_pb2 as google_dot_protobuf_dot_struct__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n-dwango/nicolive/chat/data/atoms/akashic.proto\x12\x1f\x64wango.nicolive.chat.data.atoms\x1a\x1cgoogle/protobuf/struct.proto\"\x86\x01\n\x13\x41kashicMessageEvent\x12\x0c\n\x04type\x18\x01 \x01(\t\x12\x0e\n\x06playId\x18\x02 \x01(\t\x12\x11\n\tignorable\x18\x03 \x01(\x08\x12\x11\n\ttransient\x18\x04 \x01(\x08\x12+\n\nparameters\x18\x05 \x01(\x0b\x32\x17.google.protobuf.Struct\"\xfa\x01\n\x13\x41kashicStateRouting\x12\r\n\x05\x65poch\x18\x01 \x01(\x03\x12\x42\n\x04join\x18\x02 \x03(\x0b\x32\x34.dwango.nicolive.chat.data.atoms.AkashicMessageEvent\x12J\n\x0c\x63ontinuation\x18\x03 \x03(\x0b\x32\x34.dwango.nicolive.chat.data.atoms.AkashicMessageEvent\x12\x44\n\x06shared\x18\x04 \x03(\x0b\x32\x34.dwango.nicolive.chat.data.atoms.AkashicMessageEventb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'dwango.nicolive.chat.data.atoms.akashic_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_AKASHICMESSAGEEVENT']._serialized_start=113
  _globals['_AKASHICMESSAGEEVENT']._serialized_end=247
  _globals['_AKASHICSTATEROUTING']._serialized_start=250
  _globals['_AKASHICSTATEROUTING']._serialized_end=500
# @@protoc_insertion_point(module_scope)
