"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

from collections import abc as _abc
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import struct_pb2 as _struct_pb2
from google.protobuf.internal import containers as _containers
import builtins as _builtins
import sys
import typing as _typing

if sys.version_info >= (3, 10):
    from typing import TypeAlias as _TypeAlias
else:
    from typing_extensions import TypeAlias as _TypeAlias

DESCRIPTOR: _descriptor.FileDescriptor

@_typing.final
class AkashicMessageEvent(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    TYPE_FIELD_NUMBER: _builtins.int
    PLAYID_FIELD_NUMBER: _builtins.int
    IGNORABLE_FIELD_NUMBER: _builtins.int
    TRANSIENT_FIELD_NUMBER: _builtins.int
    PARAMETERS_FIELD_NUMBER: _builtins.int
    type: _builtins.str
    playId: _builtins.str
    ignorable: _builtins.bool
    transient: _builtins.bool
    @_builtins.property
    def parameters(self) -> _struct_pb2.Struct: ...
    def __init__(
        self,
        *,
        type: _builtins.str = ...,
        playId: _builtins.str = ...,
        ignorable: _builtins.bool = ...,
        transient: _builtins.bool = ...,
        parameters: _struct_pb2.Struct | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["parameters", b"parameters"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["ignorable", b"ignorable", "parameters", b"parameters", "playId", b"playId", "transient", b"transient", "type", b"type"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___AkashicMessageEvent: _TypeAlias = AkashicMessageEvent  # noqa: Y015

@_typing.final
class AkashicStateRouting(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    EPOCH_FIELD_NUMBER: _builtins.int
    JOIN_FIELD_NUMBER: _builtins.int
    CONTINUATION_FIELD_NUMBER: _builtins.int
    SHARED_FIELD_NUMBER: _builtins.int
    epoch: _builtins.int
    @_builtins.property
    def join(self) -> _containers.RepeatedCompositeFieldContainer[Global___AkashicMessageEvent]: ...
    @_builtins.property
    def continuation(self) -> _containers.RepeatedCompositeFieldContainer[Global___AkashicMessageEvent]: ...
    @_builtins.property
    def shared(self) -> _containers.RepeatedCompositeFieldContainer[Global___AkashicMessageEvent]: ...
    def __init__(
        self,
        *,
        epoch: _builtins.int = ...,
        join: _abc.Iterable[Global___AkashicMessageEvent] | None = ...,
        continuation: _abc.Iterable[Global___AkashicMessageEvent] | None = ...,
        shared: _abc.Iterable[Global___AkashicMessageEvent] | None = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["continuation", b"continuation", "epoch", b"epoch", "join", b"join", "shared", b"shared"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___AkashicStateRouting: _TypeAlias = AkashicStateRouting  # noqa: Y015
