"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

from ndgr_client.proto.dwango.nicolive.chat.data import atoms_pb2 as _atoms_pb2
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf.internal import enum_type_wrapper as _enum_type_wrapper
import builtins as _builtins
import sys
import typing as _typing

if sys.version_info >= (3, 10):
    from typing import TypeAlias as _TypeAlias
else:
    from typing_extensions import TypeAlias as _TypeAlias

DESCRIPTOR: _descriptor.FileDescriptor

@_typing.final
class ForwardedChat(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    class _ForwardingMode:
        ValueType = _typing.NewType("ValueType", _builtins.int)
        V: _TypeAlias = ValueType  # noqa: Y015

    class _ForwardingModeEnumTypeWrapper(_enum_type_wrapper._EnumTypeWrapper[ForwardedChat._ForwardingMode.ValueType], _builtins.type):
        DESCRIPTOR: _descriptor.EnumDescriptor
        UNKNOWN: ForwardedChat._ForwardingMode.ValueType  # 0
        FROM_CRUISE: ForwardedChat._ForwardingMode.ValueType  # 1
        COLLAB_SHARING: ForwardedChat._ForwardingMode.ValueType  # 2

    class ForwardingMode(_ForwardingMode, metaclass=_ForwardingModeEnumTypeWrapper): ...
    UNKNOWN: ForwardedChat.ForwardingMode.ValueType  # 0
    FROM_CRUISE: ForwardedChat.ForwardingMode.ValueType  # 1
    COLLAB_SHARING: ForwardedChat.ForwardingMode.ValueType  # 2

    CHAT_FIELD_NUMBER: _builtins.int
    MESSAGE_ID_FIELD_NUMBER: _builtins.int
    SOURCE_LIVE_ID_FIELD_NUMBER: _builtins.int
    MODE_FIELD_NUMBER: _builtins.int
    message_id: _builtins.str
    source_live_id: _builtins.int
    mode: Global___ForwardedChat.ForwardingMode.ValueType
    @_builtins.property
    def chat(self) -> _atoms_pb2.Chat: ...
    def __init__(
        self,
        *,
        chat: _atoms_pb2.Chat | None = ...,
        message_id: _builtins.str = ...,
        source_live_id: _builtins.int = ...,
        mode: Global___ForwardedChat.ForwardingMode.ValueType = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["chat", b"chat"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["chat", b"chat", "message_id", b"message_id", "mode", b"mode", "source_live_id", b"source_live_id"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___ForwardedChat: _TypeAlias = ForwardedChat  # noqa: Y015
