# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: dwango/nicolive/chat/data/atoms/forwarded.proto
# Protobuf Python Version: 6.30.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    30,
    2,
    '',
    'dwango/nicolive/chat/data/atoms/forwarded.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from ndgr_client.proto.dwango.nicolive.chat.data import atoms_pb2 as dwango_dot_nicolive_dot_chat_dot_data_dot_atoms__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n/dwango/nicolive/chat/data/atoms/forwarded.proto\x12\x1f\x64wango.nicolive.chat.data.atoms\x1a%dwango/nicolive/chat/data/atoms.proto\"\xfb\x01\n\rForwardedChat\x12-\n\x04\x63hat\x18\x01 \x01(\x0b\x32\x1f.dwango.nicolive.chat.data.Chat\x12\x12\n\nmessage_id\x18\x02 \x01(\t\x12\x16\n\x0esource_live_id\x18\x03 \x01(\x03\x12K\n\x04mode\x18\x04 \x01(\x0e\x32=.dwango.nicolive.chat.data.atoms.ForwardedChat.ForwardingMode\"B\n\x0e\x46orwardingMode\x12\x0b\n\x07UNKNOWN\x10\x00\x12\x0f\n\x0b\x46ROM_CRUISE\x10\x01\x12\x12\n\x0e\x43OLLAB_SHARING\x10\x02\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'dwango.nicolive.chat.data.atoms.forwarded_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_FORWARDEDCHAT']._serialized_start=124
  _globals['_FORWARDEDCHAT']._serialized_end=375
  _globals['_FORWARDEDCHAT_FORWARDINGMODE']._serialized_start=309
  _globals['_FORWARDEDCHAT_FORWARDINGMODE']._serialized_end=375
# @@protoc_insertion_point(module_scope)
