# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: dwango/nicolive/chat/data/atoms/ichibalauncher.proto
# Protobuf Python Version: 6.30.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    30,
    2,
    '',
    'dwango/nicolive/chat/data/atoms/ichibalauncher.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n4dwango/nicolive/chat/data/atoms/ichibalauncher.proto\x12\x1f\x64wango.nicolive.chat.data.atoms\"\x8e\x04\n\x15IchibaLauncherItemSet\x12\r\n\x05\x65poch\x18\x01 \x01(\x03\x12J\n\x05items\x18\x02 \x03(\x0b\x32;.dwango.nicolive.chat.data.atoms.IchibaLauncherItemSet.Item\x1a\x99\x03\n\x04Item\x12\n\n\x02id\x18\x01 \x01(\t\x12\x10\n\x08\x65ntityId\x18\x02 \x01(\t\x12\x13\n\x0bserviceName\x18\x03 \x01(\t\x12\r\n\x05title\x18\x04 \x01(\t\x12\x66\n\x10launchDialogType\x18\x05 \x01(\x0e\x32L.dwango.nicolive.chat.data.atoms.IchibaLauncherItemSet.Item.LaunchDialogType\x12\x14\n\x0cthumbnailUrl\x18\x06 \x01(\t\x12\x16\n\x0ethumbnailWidth\x18\x07 \x01(\x05\x12\x17\n\x0fthumbnailHeight\x18\x08 \x01(\x05\x12\x11\n\tlaunchUrl\x18\t \x01(\t\x12\x18\n\x0b\x61\x64\x64\x65\x64UserId\x18\n \x01(\tH\x00\x88\x01\x01\x12\x16\n\treportUrl\x18\x0b \x01(\tH\x01\x88\x01\x01\x12\x0f\n\x07running\x18\x0c \x01(\x08\",\n\x10LaunchDialogType\x12\t\n\x05SMALL\x10\x00\x12\r\n\tRICHIVIEW\x10\x01\x42\x0e\n\x0c_addedUserIdB\x0c\n\n_reportUrlb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'dwango.nicolive.chat.data.atoms.ichibalauncher_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_ICHIBALAUNCHERITEMSET']._serialized_start=90
  _globals['_ICHIBALAUNCHERITEMSET']._serialized_end=616
  _globals['_ICHIBALAUNCHERITEMSET_ITEM']._serialized_start=207
  _globals['_ICHIBALAUNCHERITEMSET_ITEM']._serialized_end=616
  _globals['_ICHIBALAUNCHERITEMSET_ITEM_LAUNCHDIALOGTYPE']._serialized_start=542
  _globals['_ICHIBALAUNCHERITEMSET_ITEM_LAUNCHDIALOGTYPE']._serialized_end=586
# @@protoc_insertion_point(module_scope)
