"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

from collections import abc as _abc
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf.internal import containers as _containers
from google.protobuf.internal import enum_type_wrapper as _enum_type_wrapper
import builtins as _builtins
import sys
import typing as _typing

if sys.version_info >= (3, 10):
    from typing import TypeAlias as _TypeAlias
else:
    from typing_extensions import TypeAlias as _TypeAlias

DESCRIPTOR: _descriptor.FileDescriptor

@_typing.final
class IchibaLauncherItemSet(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    @_typing.final
    class Item(_message.Message):
        DESCRIPTOR: _descriptor.Descriptor

        class _LaunchDialogType:
            ValueType = _typing.NewType("ValueType", _builtins.int)
            V: _TypeAlias = ValueType  # noqa: Y015

        class _LaunchDialogTypeEnumTypeWrapper(_enum_type_wrapper._EnumTypeWrapper[IchibaLauncherItemSet.Item._LaunchDialogType.ValueType], _builtins.type):
            DESCRIPTOR: _descriptor.EnumDescriptor
            SMALL: IchibaLauncherItemSet.Item._LaunchDialogType.ValueType  # 0
            RICHIVIEW: IchibaLauncherItemSet.Item._LaunchDialogType.ValueType  # 1

        class LaunchDialogType(_LaunchDialogType, metaclass=_LaunchDialogTypeEnumTypeWrapper): ...
        SMALL: IchibaLauncherItemSet.Item.LaunchDialogType.ValueType  # 0
        RICHIVIEW: IchibaLauncherItemSet.Item.LaunchDialogType.ValueType  # 1

        ID_FIELD_NUMBER: _builtins.int
        ENTITYID_FIELD_NUMBER: _builtins.int
        SERVICENAME_FIELD_NUMBER: _builtins.int
        TITLE_FIELD_NUMBER: _builtins.int
        LAUNCHDIALOGTYPE_FIELD_NUMBER: _builtins.int
        THUMBNAILURL_FIELD_NUMBER: _builtins.int
        THUMBNAILWIDTH_FIELD_NUMBER: _builtins.int
        THUMBNAILHEIGHT_FIELD_NUMBER: _builtins.int
        LAUNCHURL_FIELD_NUMBER: _builtins.int
        ADDEDUSERID_FIELD_NUMBER: _builtins.int
        REPORTURL_FIELD_NUMBER: _builtins.int
        RUNNING_FIELD_NUMBER: _builtins.int
        id: _builtins.str
        entityId: _builtins.str
        serviceName: _builtins.str
        title: _builtins.str
        launchDialogType: Global___IchibaLauncherItemSet.Item.LaunchDialogType.ValueType
        thumbnailUrl: _builtins.str
        thumbnailWidth: _builtins.int
        thumbnailHeight: _builtins.int
        launchUrl: _builtins.str
        addedUserId: _builtins.str
        reportUrl: _builtins.str
        running: _builtins.bool
        def __init__(
            self,
            *,
            id: _builtins.str = ...,
            entityId: _builtins.str = ...,
            serviceName: _builtins.str = ...,
            title: _builtins.str = ...,
            launchDialogType: Global___IchibaLauncherItemSet.Item.LaunchDialogType.ValueType = ...,
            thumbnailUrl: _builtins.str = ...,
            thumbnailWidth: _builtins.int = ...,
            thumbnailHeight: _builtins.int = ...,
            launchUrl: _builtins.str = ...,
            addedUserId: _builtins.str | None = ...,
            reportUrl: _builtins.str | None = ...,
            running: _builtins.bool = ...,
        ) -> None: ...
        _HasFieldArgType: _TypeAlias = _typing.Literal["_addedUserId", b"_addedUserId", "_reportUrl", b"_reportUrl", "addedUserId", b"addedUserId", "reportUrl", b"reportUrl"]  # noqa: Y015
        def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
        _ClearFieldArgType: _TypeAlias = _typing.Literal["_addedUserId", b"_addedUserId", "_reportUrl", b"_reportUrl", "addedUserId", b"addedUserId", "entityId", b"entityId", "id", b"id", "launchDialogType", b"launchDialogType", "launchUrl", b"launchUrl", "reportUrl", b"reportUrl", "running", b"running", "serviceName", b"serviceName", "thumbnailHeight", b"thumbnailHeight", "thumbnailUrl", b"thumbnailUrl", "thumbnailWidth", b"thumbnailWidth", "title", b"title"]  # noqa: Y015
        def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
        _WhichOneofReturnType__addedUserId: _TypeAlias = _typing.Literal["addedUserId"]  # noqa: Y015
        _WhichOneofArgType__addedUserId: _TypeAlias = _typing.Literal["_addedUserId", b"_addedUserId"]  # noqa: Y015
        _WhichOneofReturnType__reportUrl: _TypeAlias = _typing.Literal["reportUrl"]  # noqa: Y015
        _WhichOneofArgType__reportUrl: _TypeAlias = _typing.Literal["_reportUrl", b"_reportUrl"]  # noqa: Y015
        @_typing.overload
        def WhichOneof(self, oneof_group: _WhichOneofArgType__addedUserId) -> _WhichOneofReturnType__addedUserId | None: ...
        @_typing.overload
        def WhichOneof(self, oneof_group: _WhichOneofArgType__reportUrl) -> _WhichOneofReturnType__reportUrl | None: ...

    EPOCH_FIELD_NUMBER: _builtins.int
    ITEMS_FIELD_NUMBER: _builtins.int
    epoch: _builtins.int
    @_builtins.property
    def items(self) -> _containers.RepeatedCompositeFieldContainer[Global___IchibaLauncherItemSet.Item]: ...
    def __init__(
        self,
        *,
        epoch: _builtins.int = ...,
        items: _abc.Iterable[Global___IchibaLauncherItemSet.Item] | None = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["epoch", b"epoch", "items", b"items"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___IchibaLauncherItemSet: _TypeAlias = IchibaLauncherItemSet  # noqa: Y015
