"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

from collections import abc as _abc
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import timestamp_pb2 as _timestamp_pb2
from google.protobuf.internal import containers as _containers
from google.protobuf.internal import enum_type_wrapper as _enum_type_wrapper
import builtins as _builtins
import sys
import typing as _typing

if sys.version_info >= (3, 10):
    from typing import TypeAlias as _TypeAlias
else:
    from typing_extensions import TypeAlias as _TypeAlias

DESCRIPTOR: _descriptor.FileDescriptor

@_typing.final
class ModeratorUserInfo(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    USER_ID_FIELD_NUMBER: _builtins.int
    NICKNAME_FIELD_NUMBER: _builtins.int
    ICONURL_FIELD_NUMBER: _builtins.int
    user_id: _builtins.int
    nickname: _builtins.str
    iconUrl: _builtins.str
    def __init__(
        self,
        *,
        user_id: _builtins.int = ...,
        nickname: _builtins.str | None = ...,
        iconUrl: _builtins.str | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["_iconUrl", b"_iconUrl", "_nickname", b"_nickname", "iconUrl", b"iconUrl", "nickname", b"nickname"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["_iconUrl", b"_iconUrl", "_nickname", b"_nickname", "iconUrl", b"iconUrl", "nickname", b"nickname", "user_id", b"user_id"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    _WhichOneofReturnType__iconUrl: _TypeAlias = _typing.Literal["iconUrl"]  # noqa: Y015
    _WhichOneofArgType__iconUrl: _TypeAlias = _typing.Literal["_iconUrl", b"_iconUrl"]  # noqa: Y015
    _WhichOneofReturnType__nickname: _TypeAlias = _typing.Literal["nickname"]  # noqa: Y015
    _WhichOneofArgType__nickname: _TypeAlias = _typing.Literal["_nickname", b"_nickname"]  # noqa: Y015
    @_typing.overload
    def WhichOneof(self, oneof_group: _WhichOneofArgType__iconUrl) -> _WhichOneofReturnType__iconUrl | None: ...
    @_typing.overload
    def WhichOneof(self, oneof_group: _WhichOneofArgType__nickname) -> _WhichOneofReturnType__nickname | None: ...

Global___ModeratorUserInfo: _TypeAlias = ModeratorUserInfo  # noqa: Y015

@_typing.final
class ModeratorUpdated(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    class _ModeratorOperation:
        ValueType = _typing.NewType("ValueType", _builtins.int)
        V: _TypeAlias = ValueType  # noqa: Y015

    class _ModeratorOperationEnumTypeWrapper(_enum_type_wrapper._EnumTypeWrapper[ModeratorUpdated._ModeratorOperation.ValueType], _builtins.type):
        DESCRIPTOR: _descriptor.EnumDescriptor
        ADD: ModeratorUpdated._ModeratorOperation.ValueType  # 0
        DELETE: ModeratorUpdated._ModeratorOperation.ValueType  # 1

    class ModeratorOperation(_ModeratorOperation, metaclass=_ModeratorOperationEnumTypeWrapper): ...
    ADD: ModeratorUpdated.ModeratorOperation.ValueType  # 0
    DELETE: ModeratorUpdated.ModeratorOperation.ValueType  # 1

    OPERATION_FIELD_NUMBER: _builtins.int
    OPERATOR_FIELD_NUMBER: _builtins.int
    UPDATEDAT_FIELD_NUMBER: _builtins.int
    operation: Global___ModeratorUpdated.ModeratorOperation.ValueType
    @_builtins.property
    def operator(self) -> Global___ModeratorUserInfo: ...
    @_builtins.property
    def updatedAt(self) -> _timestamp_pb2.Timestamp: ...
    def __init__(
        self,
        *,
        operation: Global___ModeratorUpdated.ModeratorOperation.ValueType = ...,
        operator: Global___ModeratorUserInfo | None = ...,
        updatedAt: _timestamp_pb2.Timestamp | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["operator", b"operator", "updatedAt", b"updatedAt"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["operation", b"operation", "operator", b"operator", "updatedAt", b"updatedAt"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___ModeratorUpdated: _TypeAlias = ModeratorUpdated  # noqa: Y015

@_typing.final
class SSNGUpdated(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    class _SSNGOperation:
        ValueType = _typing.NewType("ValueType", _builtins.int)
        V: _TypeAlias = ValueType  # noqa: Y015

    class _SSNGOperationEnumTypeWrapper(_enum_type_wrapper._EnumTypeWrapper[SSNGUpdated._SSNGOperation.ValueType], _builtins.type):
        DESCRIPTOR: _descriptor.EnumDescriptor
        ADD: SSNGUpdated._SSNGOperation.ValueType  # 0
        DELETE: SSNGUpdated._SSNGOperation.ValueType  # 1

    class SSNGOperation(_SSNGOperation, metaclass=_SSNGOperationEnumTypeWrapper): ...
    ADD: SSNGUpdated.SSNGOperation.ValueType  # 0
    DELETE: SSNGUpdated.SSNGOperation.ValueType  # 1

    class _SSNGType:
        ValueType = _typing.NewType("ValueType", _builtins.int)
        V: _TypeAlias = ValueType  # noqa: Y015

    class _SSNGTypeEnumTypeWrapper(_enum_type_wrapper._EnumTypeWrapper[SSNGUpdated._SSNGType.ValueType], _builtins.type):
        DESCRIPTOR: _descriptor.EnumDescriptor
        USER: SSNGUpdated._SSNGType.ValueType  # 0
        WORD: SSNGUpdated._SSNGType.ValueType  # 1
        COMMAND: SSNGUpdated._SSNGType.ValueType  # 2

    class SSNGType(_SSNGType, metaclass=_SSNGTypeEnumTypeWrapper): ...
    USER: SSNGUpdated.SSNGType.ValueType  # 0
    WORD: SSNGUpdated.SSNGType.ValueType  # 1
    COMMAND: SSNGUpdated.SSNGType.ValueType  # 2

    class _SSNGOperatorType:
        ValueType = _typing.NewType("ValueType", _builtins.int)
        V: _TypeAlias = ValueType  # noqa: Y015

    class _SSNGOperatorTypeEnumTypeWrapper(_enum_type_wrapper._EnumTypeWrapper[SSNGUpdated._SSNGOperatorType.ValueType], _builtins.type):
        DESCRIPTOR: _descriptor.EnumDescriptor
        MODERATOR: SSNGUpdated._SSNGOperatorType.ValueType  # 0
        BROADCASTER: SSNGUpdated._SSNGOperatorType.ValueType  # 1

    class SSNGOperatorType(_SSNGOperatorType, metaclass=_SSNGOperatorTypeEnumTypeWrapper): ...
    MODERATOR: SSNGUpdated.SSNGOperatorType.ValueType  # 0
    BROADCASTER: SSNGUpdated.SSNGOperatorType.ValueType  # 1

    OPERATION_FIELD_NUMBER: _builtins.int
    SSNG_ID_FIELD_NUMBER: _builtins.int
    OPERATOR_FIELD_NUMBER: _builtins.int
    TYPE_FIELD_NUMBER: _builtins.int
    SOURCE_FIELD_NUMBER: _builtins.int
    UPDATEDAT_FIELD_NUMBER: _builtins.int
    OPERATOR_TYPE_FIELD_NUMBER: _builtins.int
    operation: Global___SSNGUpdated.SSNGOperation.ValueType
    ssng_id: _builtins.int
    type: Global___SSNGUpdated.SSNGType.ValueType
    source: _builtins.str
    operator_type: Global___SSNGUpdated.SSNGOperatorType.ValueType
    @_builtins.property
    def operator(self) -> Global___ModeratorUserInfo: ...
    @_builtins.property
    def updatedAt(self) -> _timestamp_pb2.Timestamp: ...
    def __init__(
        self,
        *,
        operation: Global___SSNGUpdated.SSNGOperation.ValueType = ...,
        ssng_id: _builtins.int = ...,
        operator: Global___ModeratorUserInfo | None = ...,
        type: Global___SSNGUpdated.SSNGType.ValueType | None = ...,
        source: _builtins.str | None = ...,
        updatedAt: _timestamp_pb2.Timestamp | None = ...,
        operator_type: Global___SSNGUpdated.SSNGOperatorType.ValueType = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["_source", b"_source", "_type", b"_type", "_updatedAt", b"_updatedAt", "operator", b"operator", "source", b"source", "type", b"type", "updatedAt", b"updatedAt"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["_source", b"_source", "_type", b"_type", "_updatedAt", b"_updatedAt", "operation", b"operation", "operator", b"operator", "operator_type", b"operator_type", "source", b"source", "ssng_id", b"ssng_id", "type", b"type", "updatedAt", b"updatedAt"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    _WhichOneofReturnType__source: _TypeAlias = _typing.Literal["source"]  # noqa: Y015
    _WhichOneofArgType__source: _TypeAlias = _typing.Literal["_source", b"_source"]  # noqa: Y015
    _WhichOneofReturnType__type: _TypeAlias = _typing.Literal["type"]  # noqa: Y015
    _WhichOneofArgType__type: _TypeAlias = _typing.Literal["_type", b"_type"]  # noqa: Y015
    _WhichOneofReturnType__updatedAt: _TypeAlias = _typing.Literal["updatedAt"]  # noqa: Y015
    _WhichOneofArgType__updatedAt: _TypeAlias = _typing.Literal["_updatedAt", b"_updatedAt"]  # noqa: Y015
    @_typing.overload
    def WhichOneof(self, oneof_group: _WhichOneofArgType__source) -> _WhichOneofReturnType__source | None: ...
    @_typing.overload
    def WhichOneof(self, oneof_group: _WhichOneofArgType__type) -> _WhichOneofReturnType__type | None: ...
    @_typing.overload
    def WhichOneof(self, oneof_group: _WhichOneofArgType__updatedAt) -> _WhichOneofReturnType__updatedAt | None: ...

Global___SSNGUpdated: _TypeAlias = SSNGUpdated  # noqa: Y015

@_typing.final
class ModerationAnnouncement(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    class _GuidelineItem:
        ValueType = _typing.NewType("ValueType", _builtins.int)
        V: _TypeAlias = ValueType  # noqa: Y015

    class _GuidelineItemEnumTypeWrapper(_enum_type_wrapper._EnumTypeWrapper[ModerationAnnouncement._GuidelineItem.ValueType], _builtins.type):
        DESCRIPTOR: _descriptor.EnumDescriptor
        UNKNOWN: ModerationAnnouncement._GuidelineItem.ValueType  # 0
        SEXUAL: ModerationAnnouncement._GuidelineItem.ValueType  # 1
        SPAM: ModerationAnnouncement._GuidelineItem.ValueType  # 2
        SLANDER: ModerationAnnouncement._GuidelineItem.ValueType  # 3
        PERSONAL_INFORMATION: ModerationAnnouncement._GuidelineItem.ValueType  # 4

    class GuidelineItem(_GuidelineItem, metaclass=_GuidelineItemEnumTypeWrapper): ...
    UNKNOWN: ModerationAnnouncement.GuidelineItem.ValueType  # 0
    SEXUAL: ModerationAnnouncement.GuidelineItem.ValueType  # 1
    SPAM: ModerationAnnouncement.GuidelineItem.ValueType  # 2
    SLANDER: ModerationAnnouncement.GuidelineItem.ValueType  # 3
    PERSONAL_INFORMATION: ModerationAnnouncement.GuidelineItem.ValueType  # 4

    MESSAGE_FIELD_NUMBER: _builtins.int
    GUIDELINEITEMS_FIELD_NUMBER: _builtins.int
    UPDATEDAT_FIELD_NUMBER: _builtins.int
    message: _builtins.str
    @_builtins.property
    def guidelineItems(self) -> _containers.RepeatedScalarFieldContainer[Global___ModerationAnnouncement.GuidelineItem.ValueType]: ...
    @_builtins.property
    def updatedAt(self) -> _timestamp_pb2.Timestamp: ...
    def __init__(
        self,
        *,
        message: _builtins.str | None = ...,
        guidelineItems: _abc.Iterable[Global___ModerationAnnouncement.GuidelineItem.ValueType] | None = ...,
        updatedAt: _timestamp_pb2.Timestamp | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["_message", b"_message", "message", b"message", "updatedAt", b"updatedAt"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["_message", b"_message", "guidelineItems", b"guidelineItems", "message", b"message", "updatedAt", b"updatedAt"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    _WhichOneofReturnType__message: _TypeAlias = _typing.Literal["message"]  # noqa: Y015
    _WhichOneofArgType__message: _TypeAlias = _typing.Literal["_message", b"_message"]  # noqa: Y015
    def WhichOneof(self, oneof_group: _WhichOneofArgType__message) -> _WhichOneofReturnType__message | None: ...

Global___ModerationAnnouncement: _TypeAlias = ModerationAnnouncement  # noqa: Y015
