# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: dwango/nicolive/chat/data/atoms/notifications.proto
# Protobuf Python Version: 6.30.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    30,
    2,
    '',
    'dwango/nicolive/chat/data/atoms/notifications.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n3dwango/nicolive/chat/data/atoms/notifications.proto\x12\x1f\x64wango.nicolive.chat.data.atoms\"\xe2\x02\n\x14SimpleNotificationV2\x12T\n\x04type\x18\x01 \x01(\x0e\x32\x46.dwango.nicolive.chat.data.atoms.SimpleNotificationV2.NotificationType\x12\x0f\n\x07message\x18\x02 \x01(\t\x12\x15\n\rshow_in_telop\x18\x03 \x01(\x08\x12\x14\n\x0cshow_in_list\x18\x04 \x01(\x08\"\xb5\x01\n\x10NotificationType\x12\x0b\n\x07UNKNOWN\x10\x00\x12\n\n\x06ICHIBA\x10\x01\x12\x0b\n\x07\x45MOTION\x10\x02\x12\n\n\x06\x43RUISE\x10\x03\x12\x14\n\x10PROGRAM_EXTENDED\x10\x04\x12\x0e\n\nRANKING_IN\x10\x05\x12\x0b\n\x07VISITED\x10\x06\x12\x18\n\x14SUPPORTER_REGISTERED\x10\x07\x12\x11\n\rUSER_LEVEL_UP\x10\x08\x12\x0f\n\x0bUSER_FOLLOW\x10\tb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'dwango.nicolive.chat.data.atoms.notifications_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_SIMPLENOTIFICATIONV2']._serialized_start=89
  _globals['_SIMPLENOTIFICATIONV2']._serialized_end=443
  _globals['_SIMPLENOTIFICATIONV2_NOTIFICATIONTYPE']._serialized_start=262
  _globals['_SIMPLENOTIFICATIONV2_NOTIFICATIONTYPE']._serialized_end=443
# @@protoc_insertion_point(module_scope)
