"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf.internal import enum_type_wrapper as _enum_type_wrapper
import builtins as _builtins
import sys
import typing as _typing

if sys.version_info >= (3, 10):
    from typing import TypeAlias as _TypeAlias
else:
    from typing_extensions import TypeAlias as _TypeAlias

DESCRIPTOR: _descriptor.FileDescriptor

@_typing.final
class SimpleNotificationV2(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    class _NotificationType:
        ValueType = _typing.NewType("ValueType", _builtins.int)
        V: _TypeAlias = ValueType  # noqa: Y015

    class _NotificationTypeEnumTypeWrapper(_enum_type_wrapper._EnumTypeWrapper[SimpleNotificationV2._NotificationType.ValueType], _builtins.type):
        DESCRIPTOR: _descriptor.EnumDescriptor
        UNKNOWN: SimpleNotificationV2._NotificationType.ValueType  # 0
        ICHIBA: SimpleNotificationV2._NotificationType.ValueType  # 1
        EMOTION: SimpleNotificationV2._NotificationType.ValueType  # 2
        CRUISE: SimpleNotificationV2._NotificationType.ValueType  # 3
        PROGRAM_EXTENDED: SimpleNotificationV2._NotificationType.ValueType  # 4
        RANKING_IN: SimpleNotificationV2._NotificationType.ValueType  # 5
        VISITED: SimpleNotificationV2._NotificationType.ValueType  # 6
        SUPPORTER_REGISTERED: SimpleNotificationV2._NotificationType.ValueType  # 7
        USER_LEVEL_UP: SimpleNotificationV2._NotificationType.ValueType  # 8
        USER_FOLLOW: SimpleNotificationV2._NotificationType.ValueType  # 9

    class NotificationType(_NotificationType, metaclass=_NotificationTypeEnumTypeWrapper): ...
    UNKNOWN: SimpleNotificationV2.NotificationType.ValueType  # 0
    ICHIBA: SimpleNotificationV2.NotificationType.ValueType  # 1
    EMOTION: SimpleNotificationV2.NotificationType.ValueType  # 2
    CRUISE: SimpleNotificationV2.NotificationType.ValueType  # 3
    PROGRAM_EXTENDED: SimpleNotificationV2.NotificationType.ValueType  # 4
    RANKING_IN: SimpleNotificationV2.NotificationType.ValueType  # 5
    VISITED: SimpleNotificationV2.NotificationType.ValueType  # 6
    SUPPORTER_REGISTERED: SimpleNotificationV2.NotificationType.ValueType  # 7
    USER_LEVEL_UP: SimpleNotificationV2.NotificationType.ValueType  # 8
    USER_FOLLOW: SimpleNotificationV2.NotificationType.ValueType  # 9

    TYPE_FIELD_NUMBER: _builtins.int
    MESSAGE_FIELD_NUMBER: _builtins.int
    SHOW_IN_TELOP_FIELD_NUMBER: _builtins.int
    SHOW_IN_LIST_FIELD_NUMBER: _builtins.int
    type: Global___SimpleNotificationV2.NotificationType.ValueType
    message: _builtins.str
    show_in_telop: _builtins.bool
    show_in_list: _builtins.bool
    def __init__(
        self,
        *,
        type: Global___SimpleNotificationV2.NotificationType.ValueType = ...,
        message: _builtins.str = ...,
        show_in_telop: _builtins.bool = ...,
        show_in_list: _builtins.bool = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["message", b"message", "show_in_list", b"show_in_list", "show_in_telop", b"show_in_telop", "type", b"type"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___SimpleNotificationV2: _TypeAlias = SimpleNotificationV2  # noqa: Y015
