"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf.internal import enum_type_wrapper as _enum_type_wrapper
import builtins as _builtins
import sys
import typing as _typing

if sys.version_info >= (3, 10):
    from typing import TypeAlias as _TypeAlias
else:
    from typing_extensions import TypeAlias as _TypeAlias

DESCRIPTOR: _descriptor.FileDescriptor

@_typing.final
class StreamStateChange(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    class _State:
        ValueType = _typing.NewType("ValueType", _builtins.int)
        V: _TypeAlias = ValueType  # noqa: Y015

    class _StateEnumTypeWrapper(_enum_type_wrapper._EnumTypeWrapper[StreamStateChange._State.ValueType], _builtins.type):
        DESCRIPTOR: _descriptor.EnumDescriptor
        PASSTHROUGH: StreamStateChange._State.ValueType  # 0
        PROCESSED: StreamStateChange._State.ValueType  # 1

    class State(_State, metaclass=_StateEnumTypeWrapper): ...
    PASSTHROUGH: StreamStateChange.State.ValueType  # 0
    PROCESSED: StreamStateChange.State.ValueType  # 1

    EPOCH_FIELD_NUMBER: _builtins.int
    STATE_FIELD_NUMBER: _builtins.int
    epoch: _builtins.int
    state: Global___StreamStateChange.State.ValueType
    def __init__(
        self,
        *,
        epoch: _builtins.int = ...,
        state: Global___StreamStateChange.State.ValueType = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["epoch", b"epoch", "state", b"state"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___StreamStateChange: _TypeAlias = StreamStateChange  # noqa: Y015
