# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: dwango/nicolive/chat/data/atoms/streamstate.proto
# Protobuf Python Version: 6.30.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    30,
    2,
    '',
    'dwango/nicolive/chat/data/atoms/streamstate.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n1dwango/nicolive/chat/data/atoms/streamstate.proto\x12\x1f\x64wango.nicolive.chat.data.atoms\"\x94\x01\n\x11StreamStateChange\x12\r\n\x05\x65poch\x18\x01 \x01(\x03\x12G\n\x05state\x18\x02 \x01(\x0e\x32\x38.dwango.nicolive.chat.data.atoms.StreamStateChange.State\"\'\n\x05State\x12\x0f\n\x0bPASSTHROUGH\x10\x00\x12\r\n\tPROCESSED\x10\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'dwango.nicolive.chat.data.atoms.streamstate_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_STREAMSTATECHANGE']._serialized_start=87
  _globals['_STREAMSTATECHANGE']._serialized_end=235
  _globals['_STREAMSTATECHANGE_STATE']._serialized_start=196
  _globals['_STREAMSTATECHANGE_STATE']._serialized_end=235
# @@protoc_insertion_point(module_scope)
